### ISSUE TITLE
[Feature Request] Python 3 Compatibility

### ISSUE THREAD

**Issue by ido-nl** [ElectricSquid/OctoPrint-PrintTrack#1]
Please add Python 3 Compatibility as outlined [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html).

**Comment by ElectricSquid** [comment]
Was not aware of the switch to Python 3, will get that knocked out. Thanks for the heads up!

**Comment by ElectricSquid** [comment]
Python3 support has been added via 75c241c. Just waiting on it to get added to the plugin repository, then you should be able to update it through the plugin manager!

**Comment by ido-nl** [comment]
Thanks, thats a quick response. I will see the Octoprint update message when its ready
